import Head from "next/head";
import Image from "next/image";
import { Roboto_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

const roboto_mono = Roboto_Mono({
    // weight: "400",
    subsets: ["latin"],
    style: "normal",
});

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div>
                    <h1 className={roboto_mono.className}>
                        Hi This is Home Page!
                    </h1>
                </div>
            </main>
        </>
    );
}
